version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 4000:4000
      - 9229:9229

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    links:
      - backend
    ports:
      - 3000:3000
